[colors]
foreground = "#cdcae4"
background = "#191724"
cursor_fg = "#191724"
cursor_bg = "#cdcae4"
cursor_border = "#cdcae4"
selection_fg = "none"
selection_bg = "#304259"
scrollbar_thumb = "#635e7f"
split = "#2c2841"

ansi = [
    "#2c2841",
    "#eb6f92",
    "#94c68d",
    "#f4c276",
    "#5aaacc",
    "#c4a7e7",
    "#9ccfd8",
    "#8f8aae",
]

brights = [
    "#635e7f",
    "#ff82a4",
    "#a7daa0",
    "#ffd689",
    "#6dbddf",
    "#d7bafb",
    "#afe3ec",
    "#cdcae4",
]

[colors.tab_bar]
background = "#191724"
inactive_tab_edge = "#191724"

[colors.tab_bar.active_tab]
bg_color = "#5aaacc"
fg_color = "#191724"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#2c2841"
fg_color = "#635e7f"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#36314f"
fg_color = "#8f8aae"

[colors.tab_bar.new_tab]
bg_color = "#2c2841"
fg_color = "#635e7f"

[colors.tab_bar.new_tab_hover]
bg_color = "#36314f"
fg_color = "#cdcae4"
