[colors]
foreground = "#dddcee"
background = "#181624"
cursor_fg = "#181624"
cursor_bg = "#dddcee"
cursor_border = "#dddcee"
selection_fg = "none"
selection_bg = "#2b3b51"
scrollbar_thumb = "#625f7e"
split = "#2b283f"

ansi = [
    "#2b283f",
    "#e97294",
    "#91c488",
    "#f3c175",
    "#52abcf",
    "#c69ff7",
    "#96cfd9",
    "#9d9abc",
]

brights = [
    "#625f7e",
    "#fe85a6",
    "#a3d89b",
    "#ffd588",
    "#66bee3",
    "#dab2ff",
    "#a9e3ed",
    "#dddcee",
]

[colors.tab_bar]
background = "#181624"
inactive_tab_edge = "#181624"

[colors.tab_bar.active_tab]
bg_color = "#52abcf"
fg_color = "#181624"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#2b283f"
fg_color = "#625f7e"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#35314c"
fg_color = "#9d9abc"

[colors.tab_bar.new_tab]
bg_color = "#2b283f"
fg_color = "#625f7e"

[colors.tab_bar.new_tab_hover]
bg_color = "#35314c"
fg_color = "#dddcee"
