[colors]
foreground=cdcbdd
background=181624
selection-background=2b3b51

# Black
regular0=2b283f
bright0=625f7e

# Red
regular1=e97294
bright1=fe85a6

# Green
regular2=91c488
bright2=a3d89b

# Yellow
regular3=f3c175
bright3=ffd588

# Blue
regular4=52abcf
bright4=66bee3

# Magenta
regular5=c3a3ed
bright5=dab2ff

# Cyan
regular6=96cfd9
bright6=a9e3ed

# White
regular7=8e8aac
bright7=cdcbdd
