[colors]
foreground=cdcae4
background=191724
selection-background=304259

# Black
regular0=2c2841
bright0=635e7f

# Red
regular1=eb6f92
bright1=ff82a4

# Green
regular2=94c68d
bright2=a7daa0

# Yellow
regular3=f4c276
bright3=ffd689

# Blue
regular4=5aaacc
bright4=6dbddf

# Magenta
regular5=c4a7e7
bright5=d7bafb

# Cyan
regular6=9ccfd8
bright6=afe3ec

# White
regular7=8f8aae
bright7=cdcae4
