foreground #cdcae4
background #191724
selection_foreground none
selection_background #304259
cursor #cdcae4
cursor_text_color #191724

# Black
color0 #2c2841
color8 #635e7f

# Red
color1 #eb6f92
color9 #ff82a4

# Green
color2 #94c68d
color10 #a7daa0

# Yellow
color3 #f4c276
color11 #ffd689

# Blue
color4 #5aaacc
color12 #6dbddf

# Magenta
color5 #c4a7e7
color13 #d7bafb

# Cyan
color6 #9ccfd8
color14 #afe3ec

# White
color7 #8f8aae
color15 #cdcae4
