foreground #cdcbdd
background #181624
selection_foreground none
selection_background #2b3b51
cursor #cdcbdd
cursor_text_color #181624

# Black
color0 #2b283f
color8 #625f7e

# Red
color1 #e97294
color9 #fe85a6

# Green
color2 #91c488
color10 #a3d89b

# Yellow
color3 #f3c175
color11 #ffd588

# Blue
color4 #52abcf
color12 #66bee3

# Magenta
color5 #c3a3ed
color13 #dab2ff

# Cyan
color6 #96cfd9
color14 #a9e3ed

# White
color7 #8e8aac
color15 #cdcbdd
